package com.toblad.khwab.aura.model

import com.toblad.khwab.aura.world.LightingState

/**
 * Represents the complete visual state of Khwab Aura.
 *
 * Generated by ThemeEngine and consumed by the UI.
 *
 * [lighting] is the authoritative lighting state computed by [LightingEngine]
 * inside the engine pipeline. Compose layers must consume this value — they
 * must NOT create their own [LightingEngine] instances.
 *
 * [solarElevNorm] is the ONE authoritative normalised solar elevation for the
 * current theme.  It is computed once in AuraEngine.generateTheme() from the
 * real solar times (or fixed fallback) and propagated here.  All visual layers
 * MUST read this value instead of calling currentSolarElevNorm() themselves,
 * which eliminates per-layer solar-elevation drift and the 30-second step
 * problem (the theme is refreshed on a schedule; layers animate between values
 * using Compose animateColorAsState).
 *
 *   +1.0  solar noon
 *    0.0  horizon crossing (sunrise / sunset)
 *   -1.0  solar midnight (deep night)
 *
 * [moonIlluminationFraction] is the ONE authoritative lunar illumination
 * (0 = new moon, 1 = full moon) computed once in AuraEngine from
 * MoonPhaseCalculator.  Previously each of SkyLayer, StarLayer, and MoonLayer
 * independently called MoonPhaseCalculator.phaseFraction() inside a remember{}.
 * The value is stable for many hours so the computation is cheap, but having it
 * in AuraTheme makes the single-source architecture explicit and avoids any
 * subtle divergence between layers if the clock rolls past a phase boundary.
 *
 * [animationsEnabled] reflects [AuraConfig.animationsEnabled] so Compose
 * layers can gate their animation coroutines on a single flag.
 */
data class AuraTheme(

    /**
     * Current Aura lifecycle state.
     */
    val auraState: AuraState = AuraState.OFF,

    /**
     * Current phase of the day.
     */
    val timePhase: TimePhase = TimePhase.MORNING,

    /**
     * Current weather condition.
     */
    val weatherState: WeatherState = WeatherState.CLEAR,

    /**
     * Complete visual profile describing
     * how Aura should appear.
     */
    val profile: ThemeProfile = ThemeProfile(
        sky = SkyStyle.MORNING,
        clouds = CloudStyle.CLEAR,
        sun = SunStyle.MORNING,
        moon = MoonStyle.HIDDEN,
        weatherEffect = WeatherEffectStyle.NONE,
        ambientLight = AmbientLightStyle.MORNING,
        animation = AnimationStyle.CALM,
        season = Season.SUMMER,
        stormIntensity = 0.5f
    ),

    /**
     * Indicates whether Aura is enabled.
     */
    val enabled: Boolean = false,

    /**
     * Real sunrise time as a decimal hour (e.g. 6.5 = 06:30),
     * computed from the device's location via SolarCalculator.
     * Null when no location is available (fixed phase schedule is used).
     */
    val sunriseHour: Float? = null,

    /**
     * Real sunset time as a decimal hour.
     * Null when no location is available.
     */
    val sunsetHour: Float? = null,

    /**
     * True when the current TimePhase was derived from real
     * GPS-based solar data; false when the fixed approximate
     * schedule was used as a fallback.
     */
    val isSolarAccurate: Boolean = false,

    /**
     * Authoritative lighting state for this theme.
     *
     * Computed by [LightingEngine] inside [AuraEngine] — Compose
     * layers must render this value rather than recalculating lighting
     * independently.
     */
    val lighting: LightingState = LightingState(),

    /**
     * Whether Aura animations are enabled.
     * Mirrors [AuraConfig.animationsEnabled] — Compose layers gate
     * their animation coroutines on this flag.
     */
    val animationsEnabled: Boolean = true,

    /**
     * Authoritative normalised solar elevation for this theme.
     *
     * Range: [-1.0, +1.0]
     *   +1.0  →  solar noon (sun at highest elevation)
     *    0.0  →  horizon crossing (sunrise or sunset)
     *   -1.0  →  solar midnight (sun at lowest point)
     *
     * Computed once by [com.toblad.khwab.aura.engine.AuraEngine] and
     * shared with all visual layers.  Visual layers MUST use this value
     * instead of calling [com.toblad.khwab.aura.ui.currentSolarElevNorm]
     * independently so all elements share the same atmospheric reference.
     *
     * Default is 0.5 (mid-morning / mid-afternoon — clearly daytime).
     */
    val solarElevNorm: Float = 0.5f,

    /**
     * Authoritative lunar illumination fraction for this theme.
     *
     * Range: [0.0, 1.0]
     *   0.0  →  new moon  (no moonlight contribution)
     *   1.0  →  full moon (maximum moonlight contribution)
     *
     * Derived from [com.toblad.khwab.aura.sun.MoonPhaseCalculator.phaseFraction]
     * using  k = (1 − cos(2π·phase)) / 2  — the standard illuminated-fraction
     * formula.
     *
     * Computed once in [com.toblad.khwab.aura.engine.AuraEngine] so all visual
     * layers (SkyLayer, StarLayer, MoonLayer) receive the same value without each
     * independently querying MoonPhaseCalculator.
     *
     * Default is 0.0 (conservatively no moonlight until computed).
     */
    val moonIlluminationFraction: Float = 0.0f
)