package com.toblad.khwab.aura.model

import com.toblad.khwab.aura.world.LightingState

/**
 * Represents the complete visual state of Khwab Aura.
 *
 * Generated by ThemeEngine and consumed by the UI.
 *
 * [lighting] is the authoritative lighting state computed by [LightingEngine]
 * inside the engine pipeline. Compose layers must consume this value — they
 * must NOT create their own [LightingEngine] instances.
 *
 * [animationsEnabled] reflects [AuraConfig.animationsEnabled] so Compose
 * layers can gate their animation coroutines on a single flag.
 */
data class AuraTheme(

    /**
     * Current Aura lifecycle state.
     */
    val auraState: AuraState = AuraState.OFF,

    /**
     * Current phase of the day.
     */
    val timePhase: TimePhase = TimePhase.MORNING,

    /**
     * Current weather condition.
     */
    val weatherState: WeatherState = WeatherState.CLEAR,

    /**
     * Complete visual profile describing
     * how Aura should appear.
     */
    val profile: ThemeProfile = ThemeProfile(
        sky = SkyStyle.MORNING,
        clouds = CloudStyle.CLEAR,
        sun = SunStyle.MORNING,
        moon = MoonStyle.HIDDEN,
        weatherEffect = WeatherEffectStyle.NONE,
        ambientLight = AmbientLightStyle.MORNING,
        animation = AnimationStyle.CALM,
        season = Season.SUMMER,
        stormIntensity = 0.5f
    ),

    /**
     * Indicates whether Aura is enabled.
     */
    val enabled: Boolean = false,

    /**
     * Real sunrise time as a decimal hour (e.g. 6.5 = 06:30),
     * computed from the device's location via SolarCalculator.
     * Null when no location is available (fixed phase schedule is used).
     */
    val sunriseHour: Float? = null,

    /**
     * Real sunset time as a decimal hour.
     * Null when no location is available.
     */
    val sunsetHour: Float? = null,

    /**
     * True when the current TimePhase was derived from real
     * GPS-based solar data; false when the fixed approximate
     * schedule was used as a fallback.
     */
    val isSolarAccurate: Boolean = false,

    /**
     * Authoritative lighting state for this theme.
     *
     * Computed by [LightingEngine] inside [AuraEngine] — Compose
     * layers must render this value rather than recalculating lighting
     * independently.
     */
    val lighting: LightingState = LightingState(),

    /**
     * Whether Aura animations are enabled.
     * Mirrors [AuraConfig.animationsEnabled] — Compose layers gate
     * their animation coroutines on this flag.
     */
    val animationsEnabled: Boolean = true
)