package com.toblad.khwab.aura.model

/**
 * Represents the complete visual state of Khwab Aura.
 *
 * Generated by ThemeEngine and consumed by the UI.
 */
data class AuraTheme(

    /**
     * Current Aura lifecycle state.
     */
    val auraState: AuraState = AuraState.OFF,

    /**
     * Current phase of the day.
     */
    val timePhase: TimePhase = TimePhase.MORNING,

    /**
     * Current weather condition.
     */
    val weatherState: WeatherState = WeatherState.CLEAR,

    /**
     * Complete visual profile describing
     * how Aura should appear.
     */
    val profile: ThemeProfile = ThemeProfile(
        sky = SkyStyle.MORNING,
        clouds = CloudStyle.CLEAR,
        sun = SunStyle.MORNING,
        moon = MoonStyle.HIDDEN,
        weatherEffect = WeatherEffectStyle.NONE,
        ambientLight = AmbientLightStyle.MORNING,
        animation = AnimationStyle.CALM
    ),

    /**
     * Indicates whether Aura is enabled.
     */
    val enabled: Boolean = false
)

